language: php

cache:
  directories:
    - vendor

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

jobs:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer self-update --2
  - travis_retry composer install --prefer-dist --no-interaction

script: vendor/bin/phpunit --verbose
